apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
     push: false
#  googleCloudBuild:
#    projectId: ticketing-dev-426415
  artifacts:
    - image: nickolaydocker/auth
      context: auth
#    - image: us.gcr.io/ticketing-dev-426415/auth
#      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: nickolaydocker/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.js'
            dest: .
portForward: 
  - resourceType: Service
    resourceName: auth-mongo-srv
    port: 27017